config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  get '/allposts', to: 'all_posts#index'
  
  root to: 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    can :read, Post

    can :read, Comment

    return unless user.present?

    can %i[create destroy], Post, author: user

    can %i[create destroy], Comment, author: user

    # return unless user.admin?

    # can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_create do |_post|
    update_post_comments_counter
  end

  def update_post_comments_counter
    post.increment_comments_counter
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_create do |_like|
    update_post_likes_counter(true)
  end

  after_destroy do |_like|
    update_post_likes_counter(false)
  end

  def update_post_likes_counter(input)
    post.increment_likes_counter(input)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  paginates_per 3

  validates :title, :text, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, comparison: { greater_than_or_equal_to: 0 },
                                               numericality: { only_integer: true }

  after_create do |_post|
    update_user_post_counter
  end

  def increment_likes_counter(input)
    return update(likes_counter: self.likes_counter += 1) if input

    update(likes_counter: self.likes_counter -= 1)
  end

  def increment_comments_counter
    update(comments_counter: self.comments_counter += 1)
  end

  def update_user_post_counter
    author.increment_posts_counter
  end

  def most_recent_comments(limit = 5)
    comments.includes(:author).order(created_at: :desc).limit(limit)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, :bio, :photo, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def increment_posts_counter
    update(posts_counter: self.posts_counter += 1)
  end
end

app/controllers/all_posts_controller.rb
class AllPostsController < ApplicationController
  def index
    @posts = Post.includes(:author, :comments, :likes).all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: %i[index show]

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find_by(id: params[:post_id])

    @comment = Comment.new(author: current_user, post:, text: comment_params)

    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash.now[:error] = "Error: couldn't save comment"
      render :new, alert: 'Error occured!'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.post.decrement!(:comments_counter)
    comment.destroy

    flash[:success] = 'Comment deleted successfully'
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find_by(id: params[:post_id])
    user = current_user
    @like = Like.new(author: user, post:)

    if @like.save
      flash[:success] = 'Likes added successfully'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash.now[:error] = 'Error occured'
    end
  end

  def destroy
    like = Like.find_by(author_id: current_user.id)
    like.post.decrement!(:likes_counter)
    like.destroy

    flash[:success] = 'Likes removed successfully'
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find_by(id: params[:user_id])
    @posts = Post.where(author_id: params[:user_id]).page params[:page]
  end

  def show
    @comment = Comment.new
    @post = Post.includes(:author, :comments, :likes).find_by(author_id: params[:user_id],
                                                              id: params[:id]) || 'There is no post'
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author: current_user, title: post_params[:title], text: post_params[:text])
    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_path(current_user)
    else
      flash[:success] = "Invalid input, post wasn't saved"
      redirect_to new_user_post_path(current_user)
    end
  end

  def destroy
    post = Post.find_by(author_id: current_user.id)
    post.author.decrement!(:posts_counter)
    post.destroy

    flash[:success] = 'Post removed successfully'
    redirect_to user_posts_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id]) || 'There is no user'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User saved successfully'
      redirect_to users_path
    else
      flash.now[:error] = "Error: couldn't save user"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :photo)
  end
end

app/helpers/action_decider_helper.rb
module ActionDeciderHelper
  def like_action_decider(post, current_user)
    if post.respond_to?(:likes) && post.likes.find_by(author_id: current_user.id)
      {
        method: 'delete',
        url: user_post_like_path(user_id: post.author.id, post_id: post.id),
        button_text: 'Dislike'
      }
    else
      {
        method: 'post',
        url: user_post_likes_path(user_id: post.author.id, post_id: post.id),
        button_text: 'Like'
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/all_posts/index.html.erb
<h3>List of all posts:</h3>
<% @posts.each do |post| %>
    <div class="single_post">
      <div class="post-owner-info">
            <img src=<%= post.author.photo %> id="post_owner_photo" alt="post_owner_photo" />
            <a href= <%= user_path(post.author) %> class="author_info">
                <h3><%= post.author.name %></h3>
                <p id="author-bio"><%= post.author.bio %></p>
            </a>
        </div>
        <%= render partial: "posts/post", locals: { post: post, user: post.author} %>
    </div>
<% end %>

app/views/comments/new.html.erb
<h2>Create a new comment</h2>

<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <li class="comment_form"><%= form.label :"text:" %>
  <%= form.text_area :text, :required=>true, class: "input_fields" %>
  </li>
    <%= form.submit "Add comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <header>
    <div class="nav-links">
      <%= link_to "Home", users_path, id: "Home_btn" %>
      <%= link_to "Posts", allposts_path, id: "Home_btn" %>
    </div>
    <% if user_signed_in? %>
      <div class="current_user_wrapper">
        <img src=<%= current_user.photo %> id="current_user_photo" alt="current_user_photo" />
        <div class="current_user_options">
          <%= button_to "Profile", destroy_user_session_path, method: :delete, id: "log_out_btn" %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, id: "log_out_btn" %>
        </div>
      </div>
    <% end %>
    <% if !user_signed_in? && request.env['PATH_INFO'] != new_user_session_path %>
      <%= link_to "Login", new_user_session_path, id: "log_in_btn" %>
    <% end %>
  </header>
    <% if user_signed_in? %>
    <% end %>
  
  <%= yield %>
  <footer>Created by Yonas Tesfu &copy 2023</footer>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "style" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="single_comment">
    <a href= <%= user_path(comment.author) %> class="comment_user_profile">
    <img id="comment_user_photo" src= <%= comment.author.photo %> alt="user_image" />
    </a>
    <div class="comment_text_holder">
        <a href= <%= user_path(comment.author) %> class="author_info">
                <div class="commenter-name">
                    <span><strong><%= comment.author.name %></strong></span>
                    <span id="created_at"><%= ((Time.current - comment.created_at) / 60).round %>m</span>
                </div>
                <p id="author-bio"><%= post.author.bio %></p>
        </a>
        <div>
            <p><%= comment.text %></p>
            <% if can? :destroy, comment %>
                <%= button_to "Delete", user_post_comment_path(params[:user_id], post, comment), method: :delete, id: "comment_delete_btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/_post.html.erb
<a href= <%= user_post_path(user, post) %> id= <%= post.id %> class="post_link" ><h4><%= post.title%></h4>
<p><%= post.text.first(150) %></p>
<p id="comments-likes">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p></a>

app/views/posts/index.html.erb
<% if @user.nil? %>
    <p>There is no user with this id</p>
<% else %>
    <%= render partial: "/users/user", locals: { user: @user } %>
    <h3>List of all posts:</h3>
    <% if @posts.empty? %>
        <p>There are no posts by <strong><%= @user.name %></strong> currently.</p>
    <% else %>
        <% @posts.each do |post| %>
            <div class="single_post">
                <%= render partial: "post", locals: { post: post, user: @user} %>
                <div class="comment_section">
                    <% post.most_recent_comments.each do |comment| %>
                        <%= render partial: "comment", locals: { comment: comment, post: } %>
                    <% end %>
                </div>
                <% if can? :destroy, post %>
                <%= button_to "Delete", user_post_path(current_user, post), method: :delete, id: "delete_post_btn" %>
                <% end %>
            </div>
        <% end %>
    <% end %> 
<% end %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h2>Create a new post</h2>

<%= form_with model: @post, url: user_posts_path(user_id: params[:user_id]), html: { class: "form" } do |form| %>
  <li id="input_title"><%= form.label :"title:" %>
  <%= form.text_field :title, :required=>true %>
  </li>
  <li><%= form.label :"text:" %>
  <%= form.text_area :text, :required=>true %>
  </li>
    <%= form.submit "Add post" %>
<% end %>

app/views/posts/show.html.erb
<% unless @post.kind_of? String %>
    <div class="detailed_post">
        <div class="post-owner-info">
            <img src=<%= @post.author.photo %> id="post_owner_photo" alt="post_owner_photo" />
            <a href= <%= user_path(@post.author) %> class="author_info">
                <h3><%= @post.author.name %></h3>
                <p id="author-bio"><%= @post.author.bio %></p>
            </a>
        </div>
        <div id="post-container">
            <div class="post-top-section">
                <h4><%= @post.title%></h4>
                <p id="comments-likes">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
            </div>
            <p><%= @post.text %></p>
        </div>
        <div class="comment_info">
            <% @post.comments.each do |comment| %>
                <%= render partial: "comment", locals: { comment: , post: @post} %>
            <% end %>
        </div>
        <% if user_signed_in? %>
        <div class="comment_like_holder">
            <div class="commenter_section">
                <img src= <%= current_user.photo %> id="commenter_photo" />
                <%= form_with model: @comment, url: user_post_comments_path(user_id: @post.author.id, post_id: @post.id) do |form| %>
                    <%= form.text_field :text, placeholder: "Message...", :required=>true, :value=>"" %>
                <% end %>
            </div>
                <% current_state = like_action_decider(@post, current_user) %>
                <%= form_with url: current_state[:url], method: :"#{current_state[:method]}" do |form| %>
                    <%= form.submit "#{current_state[:button_text]}" %>
                <% end %>
            <% end %>
        </div>
        
    </div>
<% else %>
    <p><%= @post %>
<% end %>

app/views/users/_user.html.erb
<div id="user">
    <img id="user-img" src= <%= user&.photo %> alt="user_image"/>
    <div class="user_info">
        <h2><%= user&.name %></h2>
        <p id="user-bio"><%= user.bio %></p>
    </div>
    <p id="post-count">Number of posts: <%= user&.posts_counter %></p>
</div>

app/views/users/index.html.erb
<% if can? :create, Post %>
  <button id="create_post"><%= link_to 'Create post', new_user_post_path(current_user) %></button>
<% end %>
<h3>List of all bloggers:</h3>
<% if @users.empty? %>
  <p>There are no users to display</p>
<% else %>
    <% @users.each do |user| %>
      <a href= <%= user_path(user) %> class="single_user" id= <%= user.name %>>
        <%= render partial: "user", locals: { user: user } %>
      </a>
    <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Create a new user</h2>

<%= form_with model: @user, html: { class: "form" }  do |form| %>
  <li><%= form.label :"name:" %>
  <%= form.text_field :name, :required=>true %>
  </li>
  <li id="input_bio"><%= form.label :"bio:" %>
  <%= form.text_area :bio, :required=>true %>
  </li>
  <li><%= form.label :"photo(url):" %>
  <%= form.text_field :photo, :required=>true %>
  </li>
    <%= form.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<% unless @user.kind_of? String %>
    <%= render partial: "user", locals: { user: @user } %>
    <div id="bio">
        <h4>Bio</h4>
        <p><%= @user.bio %></p>
    </div>
    <% posts = @user.recent_posts %>
     <% posts.each do |post| %>
        <div class="single_post">
            <%= render partial: "/posts/post", locals: { post: post, user: @user} %>
        </div>
    <% end %>
    <% if posts.empty? %>
        <p>There are no posts by <strong><%= @user.name %></strong> currently.</p>
    <% end %>
    <div class="buttons_holder">
        <% unless @user.posts.empty? %>
            <button id="show_all_posts"><%= link_to 'Show all posts', user_posts_path(user_id: @user.id) %></button>
        <% end %>
    </div> 
<% else %>
    <p><%= @user %>
<% end %>